package shared.enums;

public enum RequestType {
    MESSAGE,
    UPDATE_READ_MESSAGES,
    REGISTER,
    LOGIN,
    LOGOUT,
    CREATE_CONVERSATION,
    ADD_PARTICIPANT,
    LEAVE_CONVERSATION,
    JOIN_CONVERSATION,
    ADMIN_CONVERSATION_QUERY,
    ADMIN_VIEW_CONVERSATION,
    PING
}
