package shared.enums;

public enum ResponseType {
    MESSAGE,
    READ_MESSAGES_UPDATED,
    REGISTER_RESULT,
    LOGIN_RESULT,
    CONVERSATION,
    CONVERSATION_METADATA,
    ADMIN_CONVERSATION_RESULT,
    ADMIN_VIEW_CONVERSATION_RESULT,
    LEAVE_RESULT,
    PONG,
    CONNECTED
}
